version: "3.7"
services:

  backend:
    image: doccano/doccano:backend
    build:
        context: ../
        dockerfile: ./docker/Dockerfile.prod
    volumes:
      - static_volume:/backend/staticfiles
      - media:/backend/media
      - tmp_file:/backend/filepond-temp-uploads
      - ../tools:/opt/bin
    environment:
      ADMIN_USERNAME: "${ADMIN_USERNAME}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      CELERY_BROKER_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      REDIS_URL: "redis://redis:6379/0"
      ALLOW_SIGNUP: "False"
      DEBUG: "False"
      DJANGO_SETTINGS_MODULE: "config.settings.production"
      ALLOWED_HOSTS: "localhost,127.0.0.1,doccano-backend,doccano-nginx,192.168.56.1"
      CORS_ALLOWED_ORIGINS: "http://localhost,http://127.0.0.1,http://192.168.56.1,https://localhost,https://127.0.0.1,https://192.168.56.1"
      CSRF_TRUSTED_ORIGINS: "http://localhost,http://127.0.0.1,http://192.168.56.1,https://localhost,https://127.0.0.1,https://192.168.56.1"
      SECURE_SSL_REDIRECT: "False"
    healthcheck:
      test: ["CMD", "/opt/bin/healthcheck.sh"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 180s
    depends_on:
      - postgres
      - redis
    networks:
      - network-backend
      - network-frontend

  celery:
    image: doccano/doccano:backend
    volumes:
      - media:/backend/media
      - tmp_file:/backend/filepond-temp-uploads
    entrypoint: ["/opt/bin/prod-celery.sh"]
    environment:
      PYTHONUNBUFFERED: "1"
      CELERY_BROKER_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      REDIS_URL: "redis://redis:6379/0"
      DJANGO_SETTINGS_MODULE: "config.settings.production"
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - network-backend

  flower:
    image: doccano/doccano:backend
    entrypoint: ["/opt/bin/prod-flower.sh"]
    environment:
      PYTHONUNBUFFERED: "1"
      CELERY_BROKER_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      DJANGO_SETTINGS_MODULE: "config.settings.production"
      FLOWER_BASIC_AUTH: "${FLOWER_BASIC_AUTH}" # Format "username:password"
    depends_on:
      - celery
    ports:
      - 5555:5555
    networks:
      - network-backend
      - network-frontend

  rabbitmq:
    image: rabbitmq:3.10.7-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    ports:
      - 5672:5672
    networks:
      - network-backend

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - network-backend
    volumes:
      - redis_data:/data

  nginx:
    image: doccano/doccano:frontend
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.nginx
    command: >
      /bin/sh -c
      "envsubst '
      $${WORKER_PROCESSES}
      '< /etc/nginx/nginx.conf.template
      > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
    environment:
      API_URL: "http://backend:8000"
      GOOGLE_TRACKING_ID: ""
      WORKER_PROCESSES: "auto"
    volumes:
      - static_volume:/static
      - media:/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:8080
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - network-backend
      - network-frontend

  postgres:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    networks:
      - network-backend

volumes:
  postgres_data:
  static_volume:
  media:
  tmp_file:
  redis_data:

networks:
  network-backend:
    name: doccano_backend
  network-frontend:
    name: doccano_frontend
